"""Generate the root system drawn under the sprout in the hero illustration.

Writes lib/roots.ts. Run from the project folder:  python scripts/generate-roots.py
Change SEED for a different (but similar) root shape.
"""
import math
import os
import random

SEED = 21
W, H, GROUND = 600, 680, 300
CX = 300

random.seed(SEED)
segments = []  # (path, width, order)
tips = []


def grow(x, y, ang, length, width, depth, order, gravity):
    if depth <= 0 or width < 0.45:
        tips.append((x, y, order))
        return
    a2 = ang + random.uniform(-11, 11)
    a2 += (90 - a2) * gravity
    ex = x + math.cos(math.radians(a2)) * length
    ey = y + math.sin(math.radians(a2)) * length
    if ey > H - 10 or ex < 12 or ex > W - 12:
        tips.append((x, y, order))
        return
    # smooth cubic: leave along the old heading, arrive along the new one
    c1x = x + math.cos(math.radians(ang)) * length * 0.4
    c1y = y + math.sin(math.radians(ang)) * length * 0.4
    c2x = ex - math.cos(math.radians(a2)) * length * 0.35
    c2y = ey - math.sin(math.radians(a2)) * length * 0.35
    segments.append((f"M{x:.1f} {y:.1f}C{c1x:.1f} {c1y:.1f} {c2x:.1f} {c2y:.1f} {ex:.1f} {ey:.1f}", width, order))
    grow(ex, ey, a2, length * 0.9, width * 0.8, depth - 1, order + 1, gravity)
    if random.random() < 0.42 and depth > 2:
        side = random.choice([-1, 1])
        grow(ex, ey, a2 + side * random.uniform(30, 50), length * random.uniform(0.55, 0.72), width * 0.58, depth - 2, order + 1, gravity)


# taproot and three pairs of lateral roots
grow(CX, GROUND + 2, 90, 34, 6.5, 12, 0, 0.3)
for side in (-1, 1):
    grow(CX + side * 5, GROUND + 2, 90 - side * 68, 46, 4.2, 10, 0, 0.07)
    grow(CX + side * 3, GROUND + 3, 90 - side * 42, 40, 3.6, 10, 0, 0.1)
    grow(CX + side * 2, GROUND + 4, 90 - side * 20, 34, 3.0, 9, 0, 0.14)

lines = ["// Generated by scripts/generate-roots.py - do not edit by hand.",
         f"export const ROOTS_VIEWBOX = {{ width: {W}, height: {H}, ground: {GROUND} }};",
         "export const ROOT_SEGMENTS: [string, number, number][] = ["]
lines += [f'  ["{d}", {w:.2f}, {o}],' for d, w, o in segments]
lines.append("];")
lines.append("export const ROOT_TIPS: [number, number, number][] = [")
lines += [f"  [{x:.1f}, {y:.1f}, {o}]," for x, y, o in tips if y > GROUND + 120]
lines.append("];")

out = os.path.join(os.path.dirname(__file__), "..", "lib", "roots.ts")
with open(out, "w", encoding="utf-8") as f:
    f.write("\n".join(lines) + "\n")
print(f"{len(segments)} segments, {len(tips)} tips")
